### ISSUE TITLE
build fails with 4.14.11-300.fc27.x86_64

### ISSUE THREAD

**Issue by hgruber** [imageguy/fglrx-for-Fedora#18]
with Fedora 27 a came up to this point:
[..]
  CC [M]  /usr/lib/modules/fglrx/build_mod/2.6.x/kcl.o
  CC [M]  /usr/lib/modules/fglrx/build_mod/2.6.x/kcl_wait.o
  LD [M]  /usr/lib/modules/fglrx/build_mod/2.6.x/fglrx.o
  Building modules, stage 2.
  MODPOST 1 modules
FATAL: modpost: GPL-incompatible module fglrx.ko uses GPL-only symbol 'cpu_tlbstate'
[..]
Any ideas?
Thanks for help.

**Comment by imageguy** [comment]
I haven't seen such a problem, but then I last installed on fc26 - I replaced my video card and can no longer run fglrx on my box. I'll post your problem on the community page and see if anyone has an idea.

**Comment by Chocobo-ts** [comment]
same issue on 4.13 patch on Linux Mint 18.3
possible **testing** workaround - https://askubuntu.com/a/668204
in file common/lib/modules/fglrx/build_mod/firegl_public.c

After this - building done without errors
`Loading new fglrx-core-15.302 DKMS files...
Building only for 4.13.0-26-generic
Building for architecture amd64
Building initial module for 4.13.0-26-generic
Done.`

**Comment by imageguy** [comment]
According to the answer I got to my question on the community page, patching firegl_public.c works on 4.14.11-200 at least. I'll update the patch tomorrow.

**Comment by imageguy** [comment]
I modified the 4.14 patch. I can't try it out on my machine, so please reopen if there are any problems.
